name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # === Inject GA ID from GitHub Secret into mkdocs.yml ===
      - name: Inject GA ID
        run: |
          if [ -z "${{ secrets.GA_ID }}" ]; then
            echo "GA_ID secret is not set in repo settings"; exit 1;
          fi
          sed -i 's/GA_MEASUREMENT_ID/${{ secrets.GA_ID }}/g' mkdocs.yml

      - name: Build site
        run: mkdocs build --strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
